name: DiabloLike_Final
version: 1.0
author: Doomshade
main: cz.helheim.rpg.DiabloLike
description: Plugin for Diablo-like drops from monsters
softdepend: [ EnchantmentAPI, MythicMobs, MythicLib ]
website: www.helheim.cz
database: true
commands:
  dl:
    description: The main DiabloLike command
    usage: /<command>
    permission: dl.player

permissions:
  dl.player:
    description: The permission to use basic commands
    default: true
  dl.helper:
    description: The permission for helpers
    default: false
    children:
      dl.player: true
  dl.*:
    description: The permission for admins
    default: op
    children:
      dl.helper: true
